version: '3'

services:
  postgres:
    build: 
      context: .
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
      # Change this to whatever you want to name the volume
    ports:
      - "5432:5432"

volumes:
  ny_taxi_postgres_data:
  # Change this to whatever you want to name the volume